name: React 项目自动发布
on: push

jobs:
  npm-build:
    name: NPM 工作
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 检查运行环境
        run: |
          pwd
          node -v
          npm -v

      - name: 安装项目依赖
        run: npm install

      - name: 项目构建打包
        run: npm run build

      - name: 项目部署
        run:
